### PR TITLE
Update broken_watch.json

### PR DESCRIPTION
**Pull request by Desynq**
Fixes a parsing error when loading the recipe as well as removing unnecessary code.

### CODE REVIEW

**Comment by BasiqueEvangelist** [comment]
did glisco forget to remove the recipe

image

**Comment by gliscowo** [comment]
Hey there, thank your for taking the time to correct the recipe. As @BasiqueEvangelist already mentioned however, it's actually supposed to not exist anymore. The Watch is obtained via a different in-world crafting mechanism, explained in the Almanac. As such, I'll go ahead and close the PR
Have a nice day

**Comment by Desynq** [comment]
> Hey there, thank your for taking the time to correct the recipe. As @BasiqueEvangelist already mentioned however, it's actually supposed to not exist anymore. The Watch is obtained via a different in-world crafting mechanism, explained in the Almanac. As such, I'll go ahead and close the PR Have a nice day

Why still include the recipe then if it's broken; wouldn't it just be better to remove the recipe altogether to avoid unnecessary log spam?

**Comment by Noaaan** [comment]
It will be removed for the next release

**Comment by Desynq** [comment]
> It will be removed for the next release

Ok, thanks. I'm guessing next release is on latest version (1.19)?

**Pull request closed without merging**
